//! Self-contained HTML scan report generator for Cogitator.
//!
//! Takes the findings from one scan run (a `workspace::ScanSnapshot`, once
//! reconstituted back to `scanner::ScanFinding` via `main::finding_from_ser`)
//! plus a bit of target metadata, and renders a single `.html` file: inline
//! CSS, no external assets, no JavaScript. Findings are grouped by severity
//! (Critical → High → Medium → Low → Info), each rendered as a collapsible
//! `<details>` panel showing `check_name`, `url`, `parameter`, `evidence`,
//! `request_raw`, and `response_snippet`.
//!
//! # Why escape everything
//!
//! `evidence`/`request_raw`/`response_snippet` are attacker-controlled — they
//! come straight from the scanned target's HTTP traffic. A target reflecting
//! `<script>...</script>` back at an XSS probe would otherwise get to run
//! that script *inside the report itself* the moment Johny opens it in a
//! browser. Every field that isn't a Cogitator-controlled literal is passed
//! through [`escape_html`] before it touches the output string.
//!
//! # Why no JS
//!
//! The brief mentions this report is likely headed for "browser print → PDF"
//! next. Plain `<details>`/`<summary>` gives collapsible panels with zero
//! script, and print CSS (`@media print`) forces every panel open and
//! removes screen-only chrome so the PDF shows everything rather than
//! whatever happened to be expanded on screen.

use crate::scanner::{ScanFinding, Severity};

/// Target metadata a report is generated for.
pub struct ReportMeta {
    /// Domain/host the scan targeted (informational label only).
    pub domain: String,
    /// Unix timestamp in milliseconds (UTC) the scan completed —
    /// `workspace::ScanSnapshot::timestamp_ms`.
    pub timestamp_ms: u64,
}

/// All severities, worst-first — the order findings are grouped and
/// rendered in. `pub(crate)` so `report_pdf` can reuse the same order
/// rather than maintaining a second copy that could drift out of sync.
pub(crate) const SEVERITY_ORDER: [Severity; 5] = [
    Severity::Critical,
    Severity::High,
    Severity::Medium,
    Severity::Low,
    Severity::Info,
];

/// Render `findings` + `meta` into a complete, standalone HTML document.
pub fn generate_html(findings: &[ScanFinding], meta: &ReportMeta) -> String {
    let generated_at = format_timestamp_utc(meta.timestamp_ms);
    let domain = escape_html(&meta.domain);
    let total = findings.len();

    let counts: Vec<(Severity, usize)> = SEVERITY_ORDER
        .iter()
        .map(|s| (*s, findings.iter().filter(|f| f.severity == *s).count()))
        .collect();

    let summary_badges: String = counts
        .iter()
        .map(|(sev, count)| {
            format!(
                r#"<span class="badge {class}">{label}: {count}</span>"#,
                class = severity_class(*sev),
                label = severity_label(*sev),
                count = count,
            )
        })
        .collect::<Vec<_>>()
        .join("\n    ");

    let sections: String = counts
        .iter()
        .map(|(sev, _)| {
            let group: Vec<&ScanFinding> =
                findings.iter().filter(|f| f.severity == *sev).collect();
            render_severity_section(*sev, &group)
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cogitator Scan Report — {domain}</title>
<style>
{css}
</style>
</head>
<body>
<header>
  <h1>Cogitator Scan Report</h1>
  <table class="meta">
    <tr><th>Target</th><td>{domain}</td></tr>
    <tr><th>Generated</th><td>{generated_at} UTC</td></tr>
    <tr><th>Total findings</th><td>{total}</td></tr>
  </table>
  <div class="summary">
    {summary_badges}
  </div>
</header>
<main>
{sections}
</main>
<footer>Generated by Cogitator</footer>
</body>
</html>
"#,
        domain = domain,
        css = CSS,
        generated_at = generated_at,
        total = total,
        summary_badges = summary_badges,
        sections = sections,
    )
}

/// Render one severity's `<section>` — a header with the count, and one
/// collapsible panel per finding. Emits nothing (empty string) if `group`
/// is empty, so severities with zero findings don't leave a bare empty
/// section in the output.
fn render_severity_section(sev: Severity, group: &[&ScanFinding]) -> String {
    if group.is_empty() {
        return String::new();
    }

    let panels: String = group
        .iter()
        .map(|f| render_finding_panel(f))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<section class="severity-section {class}">
  <h2>{label} <span class="count">({count})</span></h2>
  {panels}
</section>"#,
        class = severity_class(sev),
        label = severity_label(sev),
        count = group.len(),
        panels = panels,
    )
}

/// Render a single finding as a collapsible `<details>` panel. Every
/// dynamic field is HTML-escaped — see module docs for why.
fn render_finding_panel(f: &ScanFinding) -> String {
    let parameter = f.parameter.as_deref().unwrap_or("—");

    format!(
        r#"  <details class="finding">
    <summary>
      <span class="check-name">{check_name}</span>
      <span class="finding-url">{url}</span>
    </summary>
    <div class="finding-body">
      <dl>
        <dt>Parameter</dt><dd>{parameter}</dd>
        <dt>Evidence</dt><dd><pre>{evidence}</pre></dd>
        <dt>Request</dt><dd><pre>{request_raw}</pre></dd>
        <dt>Response snippet</dt><dd><pre>{response_snippet}</pre></dd>
      </dl>
    </div>
  </details>"#,
        check_name = escape_html(&f.check_name),
        url = escape_html(&f.url),
        parameter = escape_html(parameter),
        evidence = escape_html(&f.evidence),
        request_raw = escape_html(&f.request_raw),
        response_snippet = escape_html(&f.response_snippet),
    )
}

pub(crate) fn severity_label(sev: Severity) -> &'static str {
    match sev {
        Severity::Critical => "Critical",
        Severity::High => "High",
        Severity::Medium => "Medium",
        Severity::Low => "Low",
        Severity::Info => "Info",
    }
}

/// Lowercase token used as a CSS class / hook (`severity_label` lowercased),
/// kept as a separate function rather than `.to_lowercase()` at every call
/// site so the class name and display label can diverge later if needed.
fn severity_class(sev: Severity) -> &'static str {
    match sev {
        Severity::Critical => "critical",
        Severity::High => "high",
        Severity::Medium => "medium",
        Severity::Low => "low",
        Severity::Info => "info",
    }
}

/// Minimal HTML-entity escaper. Covers the five characters that matter for
/// breaking out of text content or a double-quoted attribute — sufficient
/// here since every escaped value is either dropped into text content or a
/// `<pre>` block, never into an unquoted attribute or a `<script>` context.
fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

/// Convert a Unix millisecond timestamp to a `YYYY-MM-DD HH:MM:SS` string in
/// UTC, without pulling in a date/time crate. Uses Howard Hinnant's
/// `civil_from_days` algorithm (public domain) for the calendar half; the
/// time-of-day half is plain modular arithmetic.
fn format_timestamp_utc(timestamp_ms: u64) -> String {
    let total_secs = (timestamp_ms / 1000) as i64;
    let days = total_secs.div_euclid(86_400);
    let secs_of_day = total_secs.rem_euclid(86_400);

    let (year, month, day) = civil_from_days(days);
    let hour = secs_of_day / 3600;
    let min = (secs_of_day % 3600) / 60;
    let sec = secs_of_day % 60;

    format!(
        "{:04}-{:02}-{:02} {:02}:{:02}:{:02}",
        year, month, day, hour, min, sec
    )
}

/// Days-since-epoch (1970-01-01) → (year, month, day). Standard
/// civil-from-days conversion; see
/// <http://howardhinnant.github.io/date_algorithms.html>.
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365; // [0, 399]
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    let year = if m <= 2 { y + 1 } else { y };
    (year, m, d)
}

/// Print-friendly, screen-friendly inline stylesheet. Deliberately plain —
/// no web fonts, no gradients, nothing that survives a print-to-PDF worse
/// than it looks on screen.
const CSS: &str = r#"
:root {
  --critical: #7a1f1f;
  --high: #a63d1f;
  --medium: #8a6d1f;
  --low: #2f6b3a;
  --info: #2f5580;
  --border: #ccc;
  --bg-alt: #f6f6f6;
}
* { box-sizing: border-box; }
body {
  font-family: Georgia, "Times New Roman", serif;
  color: #1a1a1a;
  margin: 2rem auto;
  max-width: 900px;
  line-height: 1.4;
}
header h1 { margin-bottom: 0.25rem; }
table.meta { border-collapse: collapse; margin: 0.75rem 0 1rem; }
table.meta th, table.meta td {
  text-align: left;
  padding: 0.15rem 0.75rem 0.15rem 0;
  font-size: 0.95rem;
}
table.meta th { color: #555; font-weight: normal; }
.summary { margin-bottom: 1.5rem; }
.badge {
  display: inline-block;
  border: 1px solid var(--border);
  border-radius: 3px;
  padding: 0.15rem 0.6rem;
  margin: 0 0.4rem 0.4rem 0;
  font-size: 0.85rem;
  font-family: Arial, sans-serif;
}
.badge.critical { border-color: var(--critical); color: var(--critical); }
.badge.high     { border-color: var(--high);     color: var(--high); }
.badge.medium   { border-color: var(--medium);   color: var(--medium); }
.badge.low      { border-color: var(--low);      color: var(--low); }
.badge.info     { border-color: var(--info);     color: var(--info); }

section.severity-section { margin-bottom: 1.75rem; }
section.severity-section h2 {
  font-family: Arial, sans-serif;
  font-size: 1.1rem;
  border-bottom: 2px solid var(--border);
  padding-bottom: 0.25rem;
}
section.critical h2 { border-bottom-color: var(--critical); color: var(--critical); }
section.high h2     { border-bottom-color: var(--high);     color: var(--high); }
section.medium h2   { border-bottom-color: var(--medium);   color: var(--medium); }
section.low h2      { border-bottom-color: var(--low);      color: var(--low); }
section.info h2     { border-bottom-color: var(--info);     color: var(--info); }
h2 .count { font-weight: normal; color: #666; font-size: 0.9rem; }

details.finding {
  border: 1px solid var(--border);
  border-radius: 4px;
  margin: 0.5rem 0;
  padding: 0.4rem 0.7rem;
  background: #fff;
}
details.finding summary {
  cursor: pointer;
  font-family: Arial, sans-serif;
  font-size: 0.95rem;
  display: flex;
  flex-wrap: wrap;
  gap: 0.6rem;
  align-items: baseline;
}
details.finding summary .check-name { font-weight: bold; }
details.finding summary .finding-url {
  color: #555;
  font-size: 0.85rem;
  word-break: break-all;
}
.finding-body { margin-top: 0.6rem; }
dl { margin: 0; }
dl dt {
  font-family: Arial, sans-serif;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.03em;
  color: #666;
  margin-top: 0.6rem;
}
dl dd { margin: 0.15rem 0 0; }
pre {
  background: var(--bg-alt);
  border: 1px solid var(--border);
  border-radius: 3px;
  padding: 0.5rem 0.6rem;
  white-space: pre-wrap;
  word-break: break-word;
  font-size: 0.85rem;
  margin: 0;
}
footer {
  margin-top: 2rem;
  font-family: Arial, sans-serif;
  font-size: 0.8rem;
  color: #888;
  border-top: 1px solid var(--border);
  padding-top: 0.5rem;
}

@media print {
  body { margin: 0.5cm; max-width: none; }
  details.finding summary { list-style: none; }
  details.finding summary::-webkit-details-marker { display: none; }
  /* Force every panel open so nothing is missing from the printed PDF,
     regardless of what was collapsed/expanded on screen. */
  details.finding { break-inside: avoid; }
  section.severity-section { break-inside: avoid-page; }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    fn finding(sev: Severity, check_name: &str) -> ScanFinding {
        ScanFinding {
            check_name: check_name.to_string(),
            severity: sev,
            evidence: "root:x:0:0".to_string(),
            request_raw: "GET /etc/passwd HTTP/1.1".to_string(),
            response_snippet: "root:x:0:0:root:/root:/bin/bash".to_string(),
            url: "http://example.com/download?file=a".to_string(),
            parameter: Some("file".to_string()),
        }
    }

    #[test]
    fn escapes_script_tags_in_evidence() {
        let mut f = finding(Severity::Critical, "XSS");
        f.evidence = "<script>alert(1)</script>".to_string();
        let html = generate_html(&[f], &ReportMeta {
            domain: "example.com".to_string(),
            timestamp_ms: 1_700_000_000_000,
        });
        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(html.contains("&lt;script&gt;"));
    }

    #[test]
    fn groups_by_severity_worst_first() {
        let findings = vec![
            finding(Severity::Info, "Info Check"),
            finding(Severity::Critical, "Critical Check"),
            finding(Severity::Medium, "Medium Check"),
        ];
        let html = generate_html(&findings, &ReportMeta {
            domain: "example.com".to_string(),
            timestamp_ms: 1_700_000_000_000,
        });
        let crit_pos = html.find("Critical Check").unwrap();
        let med_pos = html.find("Medium Check").unwrap();
        let info_pos = html.find("Info Check").unwrap();
        assert!(crit_pos < med_pos);
        assert!(med_pos < info_pos);
    }

    #[test]
    fn empty_severity_group_omits_section() {
        let findings = vec![finding(Severity::Critical, "Only Critical")];
        let html = generate_html(&findings, &ReportMeta {
            domain: "example.com".to_string(),
            timestamp_ms: 1_700_000_000_000,
        });
        assert!(!html.contains(r#"class="severity-section high""#));
        assert!(html.contains(r#"class="severity-section critical""#));
    }

    #[test]
    fn includes_all_required_fields() {
        let f = finding(Severity::High, "SQLi");
        let html = generate_html(&[f], &ReportMeta {
            domain: "target.tld".to_string(),
            timestamp_ms: 1_700_000_000_000,
        });
        assert!(html.contains("SQLi"));
        assert!(html.contains("example.com/download"));
        assert!(html.contains("file"));
        assert!(html.contains("root:x:0:0"));
        assert!(html.contains("GET /etc/passwd HTTP/1.1"));
    }

    #[test]
    fn no_external_assets() {
        let html = generate_html(&[], &ReportMeta {
            domain: "example.com".to_string(),
            timestamp_ms: 0,
        });
        assert!(!html.contains("http://") || !html.contains("<link"));
        assert!(!html.contains("<script src"));
        assert!(!html.contains("<link rel=\"stylesheet\""));
    }

    #[test]
    fn timestamp_formats_known_epoch() {
        // 1_700_000_000_000 ms == 2023-11-14 22:13:20 UTC
        assert_eq!(format_timestamp_utc(1_700_000_000_000), "2023-11-14 22:13:20");
    }

    #[test]
    fn timestamp_epoch_zero() {
        assert_eq!(format_timestamp_utc(0), "1970-01-01 00:00:00");
    }
}